services:
  backend:
    build: ./portfolio-backend
    container_name: portfolio-backend
    env_file:
      - ./portfolio-backend/.env.production
    expose:
      - "3000"

  frontend:
    build: ./portfolio-frontend
    container_name: portfolio-frontend
    ports:
      - "80:80"
    depends_on:
      - backend