services:
  backend:
    build: ./portfolio-backend
    container_name: portfolio-backend
    env_file:
      - ./portfolio-backend/.env.production
    ports:
      - "127.0.0.1:3000:3000"

  frontend:
    build: ./portfolio-frontend
    container_name: portfolio-frontend
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend